backend:
  name: git-gateway

media_folder: "public/img"

collections:
  - name: "beer"
    label: "Öl"
    folder: "public/cms/_beers"
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Kategori", name: "type", widget: "select", options: ["maltextract", "helmalt"]}
      - {label: "Beskrivning", name: "description", widget: "string"}
      - {label: "Volym (liter)", name: "volume", widget: "string"}
      - {label: "Alkohol %", name: "alcohol", widget: "string"}
      - {label: "Bryggdatum", name: "brewDate", widget: "datetime"}
      - {label: "Tappdatum", name: "tapDate", widget: "datetime"}
      - {label: "Färdigdatum", name: "drinkDate", widget: "datetime"}
      - {label: "Stil", name: "style", widget: "string"}
      - {label: "Humle", name: "hop", widget: "string"}
      - {label: "Malt", name: "malt", widget: "string"}
      - {label: "Jäst", name: "yeast", widget: "string"}
      - {label: "Länkurl", name: "linkUrl", widget: "string", required: false}
      - {label: "Länktext", name: "linkText", widget: "string", required: false}
  - name: "equipments"
    label: "Utrustning"
    folder: "public/cms/_equipments"
    create: true
    fields:
      - {label: "Kategori", name: "category", widget: "select", options: ["milling", "lautering", "boiling", "whirlpooling", "cooling", "fermenting", "maturing", "filtering", "packaging", "distribution"]}
      - {label: "Titel", name: "title", widget: "string"}