backend:
  name: git-gateway

media_folder: "public/img"

collections:
  - name: "beer"
    label: "New beer"
    folder: "public/cms/_beers"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Alcohol %", name: "alcohol", widget: "string"}
      - {label: "Brew date", name: "brewDate", widget: "datetime"}
      - {label: "Tap date", name: "tapDate", widget: "datetime"}
      - {label: "Drink date", name: "drinkDate", widget: "datetime"}
      - {label: "Style", name: "style", widget: "string"}
      - {label: "Hop", name: "hop", widget: "string"}
      - {label: "Malt", name: "malt", widget: "string"}
      - {label: "Yeast", name: "yeast", widget: "string"}
      - {label: "Link url", name: "linkUrl", widget: "string"}
      - {label: "Link text", name: "linkText", widget: "string"}